// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQjvJjD8zYfDlrkU_TIqDMy0e2IuDgwKo',
    appId: '1:1051166460410:web:7b0ff29221a7621ba23c43',
    messagingSenderId: '1051166460410',
    projectId: 'todo-a7f3b',
    authDomain: 'todo-a7f3b.firebaseapp.com',
    storageBucket: 'todo-a7f3b.appspot.com',
    measurementId: 'G-PGY1VEECE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1BMgbJeEmxgc7FI53D1lehV6xVyR-qs',
    appId: '1:1051166460410:android:f1a495c5d118d04ba23c43',
    messagingSenderId: '1051166460410',
    projectId: 'todo-a7f3b',
    storageBucket: 'todo-a7f3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2D3kR8FCvyl7BycORt6pY4sG27C4KRo',
    appId: '1:1051166460410:ios:b04322815aae24e7a23c43',
    messagingSenderId: '1051166460410',
    projectId: 'todo-a7f3b',
    storageBucket: 'todo-a7f3b.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2D3kR8FCvyl7BycORt6pY4sG27C4KRo',
    appId: '1:1051166460410:ios:b04322815aae24e7a23c43',
    messagingSenderId: '1051166460410',
    projectId: 'todo-a7f3b',
    storageBucket: 'todo-a7f3b.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQjvJjD8zYfDlrkU_TIqDMy0e2IuDgwKo',
    appId: '1:1051166460410:web:6ad3687814fdefa4a23c43',
    messagingSenderId: '1051166460410',
    projectId: 'todo-a7f3b',
    authDomain: 'todo-a7f3b.firebaseapp.com',
    storageBucket: 'todo-a7f3b.appspot.com',
    measurementId: 'G-W6EG4JS6C0',
  );
}
